/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny.AdminMeny.Kurser;

import hogwarts.Validation;
import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Lukas-PC
 */
public class RedigeraKursForm extends javax.swing.JFrame {
    private InfDB db;
    private int kursID;
    private RedigeraKurs kursPanel;
    
    private String kursNamn;
    private String startDatum, slutDatum;
    
    private int larare, amne;
    /**
     * Creates new form RedigeraKursForm
     */
    public RedigeraKursForm(InfDB db, int kursID, RedigeraKurs kursPanel) {
        this.db = db;
        this.kursID = kursID;
        this.kursPanel = kursPanel;
        initComponents();
        
        try {
            //plocka fram kursinfo
            HashMap<String, String> kursen = db.fetchRow("SELECT KURSNAMN, KURSSTART, KURSSLUT, KURSLARARE, AMNESTILLHORIGHET FROM KURS WHERE KURS_ID = " + kursID + ";");
            kursNamn = kursen.get("KURSNAMN");
            startDatum = kursen.get("KURSSTART");
            slutDatum = kursen.get("KURSSLUT");
            
            larare = Integer.parseInt(kursen.get("KURSLARARE"));
            amne = Integer.parseInt(kursen.get("AMNESTILLHORIGHET"));
            
            //populera lärarlistan
            ArrayList<HashMap<String, String>> result = db.fetchRows("SELECT FORNAMN, EFTERNAMN FROM LARARE;");
            if(result != null){
                for(HashMap<String, String> row: result){
                    //denna del lägger in namnet på läraren i listan, men separarer förnamn och efternamnet.
                    jComboBoxlarare.addItem(row.get("FORNAMN") + " " + row.get("EFTERNAMN"));
                }
            }else{
                jLabelError.setText("Det finns inga lärare");
            }
            
            //populera ämneslistan
            ArrayList<String> amnen = db.fetchColumn("SELECT AMNESNAMN FROM AMNE;");
            for(String amne : amnen){
                jComboBoxAmne.addItem(amne);
            
            }
            //Plocka upp tidigare lärare
            HashMap<String, String> lararNamn = db.fetchRow("SELECT FORNAMN, EFTERNAMN FROM LARARE WHERE LARAR_ID = "+ larare + ";");
            if(lararNamn != null){
                String ihopsattNamn;
                for(int i = 0; i < jComboBoxlarare.getItemCount(); i++){
                    ihopsattNamn = lararNamn.get("FORNAMN") + " " + lararNamn.get("EFTERNAMN");
                    if(ihopsattNamn.equals(jComboBoxlarare.getItemAt(i))){
                        //Välj tidigare lärare i listan
                        jComboBoxlarare.setSelectedIndex(i);
                    }
                }
            }
            
            //välj tidigare lärare ifån listan
            String amneNamn = db.fetchSingle("SELECT AMNESNAMN FROM AMNE WHERE AMNE_ID = "+ amne + ";");
            if(amneNamn != null){
                for(int i = 0; i < jComboBoxAmne.getItemCount(); i++){
                    if(amneNamn.equals(jComboBoxAmne.getItemAt(i))){
                        jComboBoxAmne.setSelectedIndex(i);
                    }
                }
            }
        } catch (InfException ex) {
            jLabelError.setText("SQL fel");
        }
        
        
        
        
        
        //fyll på textfälten med tidigare data
        jTextFieldKurs.setText(kursNamn);
        jTextFieldFran.setText(startDatum);
        jTextFieldTill.setText(slutDatum);
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelKurs = new javax.swing.JLabel();
        jLabelLarare = new javax.swing.JLabel();
        jTextFieldKurs = new javax.swing.JTextField();
        jComboBoxlarare = new javax.swing.JComboBox<>();
        jLabelAmne = new javax.swing.JLabel();
        jComboBoxAmne = new javax.swing.JComboBox<>();
        jTextFieldFran = new javax.swing.JTextField();
        jTextFieldTill = new javax.swing.JTextField();
        jLabelFran = new javax.swing.JLabel();
        jLabelTill = new javax.swing.JLabel();
        jButtonUppdatera = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jButtonTaBort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelKurs.setText("Kursnamn:");

        jLabelLarare.setText("Lärare:");

        jComboBoxlarare.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabelAmne.setText("Tillhör ämne:");

        jComboBoxAmne.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabelFran.setText("Från");

        jLabelTill.setText("Till");

        jButtonUppdatera.setText("Ändra");
        jButtonUppdatera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUppdateraActionPerformed(evt);
            }
        });

        jButtonTaBort.setText("Ta bort");
        jButtonTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaBortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelKurs)
                                .addComponent(jLabelLarare))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxlarare, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelFran)
                            .addGap(49, 49, 49)
                            .addComponent(jLabelTill))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldFran)
                                .addComponent(jLabelAmne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBoxAmne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTill, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUppdatera)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTaBort))
                    .addComponent(jLabelError))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKurs)
                    .addComponent(jTextFieldKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLarare)
                    .addComponent(jComboBoxlarare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAmne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAmne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFran)
                    .addComponent(jLabelTill))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUppdatera)
                    .addComponent(jButtonTaBort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabelError))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //hantera fönsterstängning
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonUppdateraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUppdateraActionPerformed
        // TODO add your handling code here:
        //Kolla så fälen inte är tomma
        boolean failed = false; 
        if (Validation.textComponentEmpty(jTextFieldKurs)) {
            failed = true; 
        }
        if (Validation.textComponentEmpty(jTextFieldFran)) {
            failed = true; 
        }
        if (Validation.textComponentEmpty(jTextFieldTill)) {
            failed = true; 
        }
       
        if(!failed){
            //Skicka data´till databasen
            try {
                String[] namn = jComboBoxlarare.getSelectedItem().toString().split(" ");
                int lararID = Integer.parseInt(db.fetchSingle("SELECT LARAR_ID FROM LARARE WHERE FORNAMN = '" + namn[0] + "' AND EFTERNAMN = '" + namn[1] + "';"));
                
                int amneID = Integer.parseInt(db.fetchSingle("SELECT AMNE_ID FROM AMNE WHERE AMNESNAMN = '" + jComboBoxAmne.getSelectedItem().toString() + "';"));
                
                db.update("UPDATE KURS SET KURSNAMN = '"+ jTextFieldKurs.getText() + "', KURSSTART = '" + jTextFieldFran.getText() + "', KURSSLUT = '" + jTextFieldTill.getText() + "', KURSLARARE = "+ lararID + ", AMNESTILLHORIGHET = " + amneID + " WHERE KURS_ID = " + kursID + ";");
                //uppdatera tidigare lista
                kursPanel.uppdateraKursLista();
            } catch (InfException ex) {
                jLabelError.setText("Fel datumformat");
            }
        }
        
    }//GEN-LAST:event_jButtonUppdateraActionPerformed

    private void jButtonTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaBortActionPerformed
        try {
            //Ta bort andvändaren samt relevant data 
            db.delete("DELETE FROM REGISTRERAD_PA WHERE KURS_ID = "+ kursID +";");
            db.delete("DELETE FROM HAR_BETYG_I WHERE KURS_ID = " + kursID + ";");
            db.delete("DELETE FROM KURS WHERE KURS_ID = " + kursID + ";");
            this.setVisible(false);
            this.dispose();
            JOptionPane.showMessageDialog(null, "Kursen togs bort!");
            kursPanel.uppdateraKursLista();
        } catch (InfException ex) {
            jLabelError.setText("SQL fel");
        }
        
    }//GEN-LAST:event_jButtonTaBortActionPerformed

 
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTaBort;
    private javax.swing.JButton jButtonUppdatera;
    private javax.swing.JComboBox<String> jComboBoxAmne;
    private javax.swing.JComboBox<String> jComboBoxlarare;
    private javax.swing.JLabel jLabelAmne;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelFran;
    private javax.swing.JLabel jLabelKurs;
    private javax.swing.JLabel jLabelLarare;
    private javax.swing.JLabel jLabelTill;
    private javax.swing.JTextField jTextFieldFran;
    private javax.swing.JTextField jTextFieldKurs;
    private javax.swing.JTextField jTextFieldTill;
    // End of variables declaration//GEN-END:variables
}
