/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny.AdminMeny.Kurser;

import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Lukas-PC
 */
public class RedigeraKurs extends javax.swing.JPanel {
    InfDB db;
    /**
     * Creates new form RedigeraKurs
     */
    public RedigeraKurs(InfDB db) {
        this.db = db;
        initComponents();
        
       uppdateraKursLista();
        
        
    }
    
    public void uppdateraKursLista(){
        jComboBoxKurs.removeAllItems();
        try {
            ArrayList<String> kurser = db.fetchColumn("SELECT KURSNAMN FROM KURS;");
            for(String kurs : kurser){
                jComboBoxKurs.addItem(kurs);
            }
        } catch (InfException ex) {
            jLabelError.setText("SQL fel");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxKurs = new javax.swing.JComboBox<>();
        jLabelKurs = new javax.swing.JLabel();
        jButtonValj = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        jComboBoxKurs.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabelKurs.setText("Välj Kurs");

        jButtonValj.setText("Välj");
        jButtonValj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelKurs)
                        .addGap(11, 11, 11)
                        .addComponent(jComboBoxKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonValj)
                    .addComponent(jLabelError))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKurs))
                .addGap(18, 18, 18)
                .addComponent(jButtonValj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabelError)
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValjActionPerformed
        try {
           //Plocka fram kursidt
            String kursIDString = db.fetchSingle("SELECT KURS_ID FROM KURS WHERE KURSNAMN = '" +  jComboBoxKurs.getSelectedItem() + "';");
            
            if(kursIDString != null){
                //oppna ett nytt fönster
                int kursID = Integer.parseInt(kursIDString);
                new RedigeraKursForm(db, kursID, this).setVisible(true);
            }else{
                 jLabelError.setText("Kursen existerar inte");
            }
        } catch (InfException ex) {
             jLabelError.setText("SQL fel");
        }
        
    }//GEN-LAST:event_jButtonValjActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValj;
    private javax.swing.JComboBox<String> jComboBoxKurs;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelKurs;
    // End of variables declaration//GEN-END:variables
}
