/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny.AdminMeny.Kurser;


import oru.inf.InfDB;

/**
 * En samlingspunkt för klasser som har med kurser att göra.
 */
public class TabbadKurser extends javax.swing.JPanel {
    private RegistreraKurs registreraKurs;
    private InfDB db;
    private RedigeraKurs redigeraKurs;
    /**
     * Creates new form TabbadKurser
     */
    public TabbadKurser(InfDB db) {
        registreraKurs = new RegistreraKurs(db);
        redigeraKurs = new RedigeraKurs(db);
        initComponents();
        
        jTabbedPaneKurser.add("Registrera kurs", registreraKurs);
        jTabbedPaneKurser.add("Redigera kurs", redigeraKurs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneKurser = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneKurser, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneKurser, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneKurser;
    // End of variables declaration//GEN-END:variables
}
