/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny;

import hogwarts.Util;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Ger läraren en möjlighet att byta ut sitt egna lösenord.
 * Den kräver att du fyller i det nuvarande lösenordet som du vill byta ut,
 * och sen ska du fylla i det nya önskade lösenordet två gånger så att det
 * stämmer överens med varandra och inte blir fel.
 *
 */
public class AndraLosenord extends javax.swing.JPanel {
    private InfDB db;
    private int lararID;
    /**
     * Creates new form AndraLosenord
     */
    public AndraLosenord(InfDB db, int lararID) {
        //initialisera fäten
        this.db = db;
        this.lararID = lararID;
        
        //Generera inehåll
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTidigareLosen = new javax.swing.JLabel();
        jLabelNyttLosen1 = new javax.swing.JLabel();
        jPasswordFieldLosen1 = new javax.swing.JPasswordField();
        jPasswordFieldTidigareLosen = new javax.swing.JPasswordField();
        jLabelNyttLosen2 = new javax.swing.JLabel();
        jPasswordFieldLosen2 = new javax.swing.JPasswordField();
        jButtonUppdatera = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        jLabelTidigareLosen.setText("Tidigare Lösenord:");

        jLabelNyttLosen1.setText("Nytt lösenord:");

        jLabelNyttLosen2.setText("Bekräfta lösenord");

        jButtonUppdatera.setText("Byt lösenord");
        jButtonUppdatera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUppdateraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNyttLosen1)
                            .addComponent(jLabelTidigareLosen)
                            .addComponent(jLabelNyttLosen2)
                            .addComponent(jButtonUppdatera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldTidigareLosen)
                            .addComponent(jPasswordFieldLosen1)
                            .addComponent(jPasswordFieldLosen2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTidigareLosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldTidigareLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabelNyttLosen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldLosen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNyttLosen2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldLosen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonUppdatera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUppdateraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUppdateraActionPerformed
        //Knappen byt läsenord är klickad
        
        //det gammla lösenordet som andvänds för verifiering
        String tidigareLosen = Util.stringFromCharArray(jPasswordFieldTidigareLosen.getPassword());
        
        //Det nya förslagna lösenordet
        String nyttlosen1 = Util.stringFromCharArray(jPasswordFieldLosen1.getPassword());
        String nyttlosen2 = Util.stringFromCharArray(jPasswordFieldLosen2.getPassword());
        
        
        try {
            //Det aktuella lösenordet
            String losen = null;
            losen = db.fetchSingle("SELECT LOSENORD FROM LARARE WHERE LARAR_ID = " + lararID + ";");
        
            //Verifiera andvändaren
            if(tidigareLosen.equals(losen)){
                //kolla så båda nya lösenorden stämmer
                if(nyttlosen1.equals(nyttlosen2)){
                    //Uppdatera lösen
                    db.update("UPDATE LARARE SET LOSENORD = '" + nyttlosen2 + "' WHERE LARAR_ID = " + lararID + ";");
                    jLabelError.setText("Uppdaterade lösen!");
                }else{
                    jLabelError.setText("Lösenorden måste stämma!");
            
                }
            }else{
                jLabelError.setText("Felaktigt lösenord");
            }
        } catch (InfException ex) {
            jLabelError.setText("Sql fel");
        }
    }//GEN-LAST:event_jButtonUppdateraActionPerformed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUppdatera;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelNyttLosen1;
    private javax.swing.JLabel jLabelNyttLosen2;
    private javax.swing.JLabel jLabelTidigareLosen;
    private javax.swing.JPasswordField jPasswordFieldLosen1;
    private javax.swing.JPasswordField jPasswordFieldLosen2;
    private javax.swing.JPasswordField jPasswordFieldTidigareLosen;
    // End of variables declaration//GEN-END:variables
}
