/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny;

import hogwarts.Util;
import hogwarts.Validation;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Denna del kan ta bort poäng eller lägga till poäng till elevhemmen. 
 * 
 */
public class HusPoang extends javax.swing.JPanel {
    private InfDB db;
    /**
     * Creates new form HusPoang
     */
    public HusPoang(InfDB db) {
        this.db = db;
        initComponents();
        
        String[] elevhemsArray = Util.elevhemsArray(db);
        
        
        for(String elevhem : elevhemsArray){
            jComboBoxElevhem.addItem(elevhem);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxElevhem = new javax.swing.JComboBox<>();
        jLabelInfo = new javax.swing.JLabel();
        jLabelPoang = new javax.swing.JLabel();
        jTextFieldPoang = new javax.swing.JTextField();
        jLabelPoangBeskrivning = new javax.swing.JLabel();
        jButtonUppdatera = new javax.swing.JButton();
        jLabelElevhem = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();

        jComboBoxElevhem.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabelInfo.setText("Lägg till / Ta bort Huspoäng");

        jLabelPoang.setText("Poäng:");

        jLabelPoangBeskrivning.setText("Skriv - innan poängen för att göra avdrag.");

        jButtonUppdatera.setText("Ändra");
        jButtonUppdatera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUppdateraActionPerformed(evt);
            }
        });

        jLabelElevhem.setText("Elevhem:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPoang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPoang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPoangBeskrivning)
                    .addComponent(jButtonUppdatera)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelElevhem)
                        .addGap(12, 12, 12)
                        .addComponent(jComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelElevhem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoang)
                    .addComponent(jTextFieldPoang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPoangBeskrivning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonUppdatera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jLabelError))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUppdateraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUppdateraActionPerformed
        // TODO add your handling code here:
        
        String elevhem = jComboBoxElevhem.getSelectedItem().toString();
        
        try {
            if(!Validation.textComponentEmpty(jTextFieldPoang)){
                int poang = Integer.parseInt(jTextFieldPoang.getText());
                
                db.update("Update ELEVHEM SET HUSPOANG = ((Select HUSPOANG FROM ELEVHEM WHERE ELEVHEMSNAMN = '" + elevhem + "')+" + poang + ") WHERE ELEVHEMSNAMN = '" + elevhem + "';");
                jLabelError.setText("Uppdaterade poängen");
            }
        } catch (NumberFormatException e){
            jLabelError.setText("skriv in en siffra");
        } catch (InfException ex) {
            jLabelError.setText("SQL ERROR ");
        } 
        
        
    }//GEN-LAST:event_jButtonUppdateraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUppdatera;
    private javax.swing.JComboBox<String> jComboBoxElevhem;
    private javax.swing.JLabel jLabelElevhem;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelPoang;
    private javax.swing.JLabel jLabelPoangBeskrivning;
    private javax.swing.JTextField jTextFieldPoang;
    // End of variables declaration//GEN-END:variables
}
