/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny;

import hogwarts.LararMeny.AdminMeny.AndraElevhem;
import hogwarts.LararMeny.AdminMeny.Kurser.TabbadKurser;
import hogwarts.LararMeny.AdminMeny.Larare.TabbadLarare;
import hogwarts.LararMeny.Elev.TabbadElev;
import hogwarts.Util;
import oru.inf.InfDB;

/**
 * Som i elevform klassen så är lärarforms klassens uppdrag att sätta upp ett "hem" för alla andra klasser som ska synas för lärare.
 * 
 */
public class LararForm extends javax.swing.JFrame {
    private int userID;
    private InfDB db;
    private AndraLosenord andraLosenord= null;
    private HusPoang husPoang = null;
    private TabbadLarare larare = null;
    
    private TabbadKurser tabbadKurser = null;
    private TabbadElev tabbadElev = null;
    
    private AndraElevhem andraElevhem = null;
    
    /**
     * Creates new form LararForm
     */
    public LararForm(InfDB db, int id) {
        userID = id;
        initComponents();
        //initialisera tabbar
        andraLosenord = new AndraLosenord(db, userID);
        
        husPoang = new HusPoang(db);
        
        andraElevhem = new AndraElevhem(db);
        larare = new TabbadLarare(db);
        tabbadKurser = new TabbadKurser(db);
        tabbadElev = new TabbadElev(db, userID);
        //lägg till tabbarna
        jTabbedPaneLarare.add("Ändra lösenord", andraLosenord);
        jTabbedPaneLarare.add("Hus poäng", husPoang);
        jTabbedPaneLarare.add("Elev", tabbadElev);
        
        //admintabbar
        if(Util.isAdmin(db, id)){
            //teacher is an admin
            
            jTabbedPaneLarare.add("Lärare", larare);
            jTabbedPaneLarare.add("Kurs", tabbadKurser);
            jTabbedPaneLarare.add("Ändra Elevhem", andraElevhem);
        }
        this.setTitle("Lärarmeny");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneLarare = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneLarare, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneLarare, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneLarare;
    // End of variables declaration//GEN-END:variables
}
