/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny.Elev;

import hogwarts.Validation;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Lägger till en kurs till en elev, samt bestämmer betyget.
 */
public class LaggaTillElevKurs extends javax.swing.JPanel {
    private InfDB db;
    /**
     * Creates new form LaggaTillElevKurs
     */
    public LaggaTillElevKurs(InfDB db) {
        
        this.db = db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldFornamn = new javax.swing.JTextField();
        jTextFieldEfternamn = new javax.swing.JTextField();
        jButtonValj = new javax.swing.JButton();
        jLabelFornamn = new javax.swing.JLabel();
        jLabelEfternamn = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();

        jButtonValj.setText("Välj");
        jButtonValj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValjActionPerformed(evt);
            }
        });

        jLabelFornamn.setText("Förnamn");

        jLabelEfternamn.setText("Efternamn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonValj)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFornamn))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEfternamn)
                            .addComponent(jTextFieldEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFornamn)
                    .addComponent(jLabelEfternamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonValj)
                .addGap(32, 32, 32)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Välj knappen klickadu
    private void jButtonValjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValjActionPerformed
        // TODO add your handling code here:
        //Validera att det finns inehåll i båda textrutor
        boolean failed = false;
        if(Validation.textComponentEmpty(jTextFieldFornamn)){
            failed = true;
            jLabelError.setText("Vänligen skriv in ett förnamn");
        }
        if(Validation.textComponentEmpty(jTextFieldEfternamn)){
            failed = true;
            jLabelError.setText("Vänligen skriv in ett efternamn");
        }
        //Alla kontroller lyckades 
        if(!failed){
            try {
                //Hämta elev ifrån namn
                String elevString = db.fetchSingle("SELECT ELEV_ID FROM ELEV WHERE FORNAMN = '"+ jTextFieldFornamn.getText() + "' AND EFTERNAMN = '"+ jTextFieldEfternamn.getText() + "';");
                
                if(elevString != null){
                    int elevID = Integer.parseInt(elevString);
                    new LaggaTillElevKursForm(db, elevID).setVisible(true);
                    jLabelError.setText("");
                }else{
                    jLabelError.setText("Det existerar ingen elev med det namnet");
                }
            } catch (InfException ex) {
                jLabelError.setText("SQL fel");
            }
        }
        
        
        
    }//GEN-LAST:event_jButtonValjActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValj;
    private javax.swing.JLabel jLabelEfternamn;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelFornamn;
    private javax.swing.JTextField jTextFieldEfternamn;
    private javax.swing.JTextField jTextFieldFornamn;
    // End of variables declaration//GEN-END:variables
}
