/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny.Elev;

import oru.inf.InfDB;

/**
 * All information om eleverna kommer samlas under denna.
 */
public class TabbadElev extends javax.swing.JPanel {
    InfDB db;
    int userID;
    
    /**
     * Creates new form Elev
     */
    public TabbadElev(InfDB db, int userID) {
        this.db = db;
        this.userID = userID;
        RegistreraElev registreraElev = new RegistreraElev(db);
        ElevInfo elevInfo = new ElevInfo(db, userID);
        LaggaTillElevKurs laggaTillElevKurs = new LaggaTillElevKurs(db);
        
        
        initComponents();
        jTabbedPaneRegistrera.add("Registrera elev", registreraElev);
        jTabbedPaneRegistrera.add("Elev info", elevInfo);
        jTabbedPaneRegistrera.add("Redigera betyg", laggaTillElevKurs);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneRegistrera = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneRegistrera, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneRegistrera, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneRegistrera;
    // End of variables declaration//GEN-END:variables
}
