/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny.AdminMeny.Larare;

import hogwarts.Util;
import hogwarts.Validation;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Registrerar en lärare till Hogwarts databas.
 */
public class RegistreraLarare extends javax.swing.JPanel {
    private InfDB db;
    /**
     * Creates new form RegistreraLärare
     */
    public RegistreraLarare(InfDB db) {
        this.db = db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfo = new javax.swing.JLabel();
        jLabelFornamn = new javax.swing.JLabel();
        jTextFieldFornamn = new javax.swing.JTextField();
        jLabelEfternamn = new javax.swing.JLabel();
        jTextFieldEfternamn = new javax.swing.JTextField();
        jLabelLosenord = new javax.swing.JLabel();
        jTextFieldLosenord = new javax.swing.JTextField();
        jButtonLaggTill = new javax.swing.JButton();
        jCheckBoxAdmin = new javax.swing.JCheckBox();
        jLabelError = new javax.swing.JLabel();

        jLabelInfo.setText("Registrera ny lärare:");

        jLabelFornamn.setText("Förnamn:");

        jLabelEfternamn.setText("Efternamn:");

        jLabelLosenord.setText("Lösenord:");

        jTextFieldLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLosenordActionPerformed(evt);
            }
        });

        jButtonLaggTill.setText("Lägg till");
        jButtonLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLaggTillActionPerformed(evt);
            }
        });

        jCheckBoxAdmin.setText("Admin");
        jCheckBoxAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxAdmin)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelInfo)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelFornamn)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldFornamn, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelEfternamn)
                                .addComponent(jLabelLosenord))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(jTextFieldEfternamn))))
                    .addComponent(jButtonLaggTill))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFornamn)
                    .addComponent(jTextFieldFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEfternamn)
                    .addComponent(jTextFieldEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLosenord)
                    .addComponent(jTextFieldLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jCheckBoxAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLaggTill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLosenordActionPerformed

    private void jButtonLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLaggTillActionPerformed
        // TODO add your handling code here:
        if(!Validation.textComponentEmpty(jTextFieldFornamn) && !Validation.textComponentEmpty(jTextFieldEfternamn) && !Validation.textComponentEmpty(jTextFieldLosenord)){
            
            String fornamn = jTextFieldFornamn.getText();
            String efternamn = jTextFieldEfternamn.getText();
            String losen = jTextFieldLosenord.getText();
            if(Validation.isValidName(fornamn) && Validation.isValidName(efternamn)){
                String treFornamn = null;
                String treEfternamn = null;
                try{
                    treFornamn = fornamn.substring(0, 3);
                }catch(StringIndexOutOfBoundsException e){
                    jLabelError.setText("Förnamnet måste vara minst tre bokstäver");
                }try{
                    treEfternamn = efternamn.substring(0, 3);
                }catch(StringIndexOutOfBoundsException e){
                    jLabelError.setText("Efternamnet måste vara minst tre bokstäver");
                }
                //validera längd på förnamn och efternamn till minst 3 styck
            
            
                boolean admin = jCheckBoxAdmin.isSelected();
            
                if(treFornamn != null && treEfternamn != null){
                    try {
                
                        if(db.fetchSingle("SELECT count(LARAR_ID) FROM LARARE WHERE FORNAMN LIKE '" + treFornamn + "%' AND EFTERNAMN LIKE '" + treEfternamn + "%';").equals("0")){
                
                            db.insert("INSERT INTO LARARE (LARAR_ID, FORNAMN, EFTERNAMN, LOSENORD, ADMINISTRATOR) VALUES (((SELECT FIRST 1 LARAR_ID FROM LARARE ORDER BY LARAR_ID DESC) + 1), '" +fornamn +"', '" + efternamn + "', '"+ losen + "', '"+ Util.convertBoolToChar(admin) +"');");
                            jLabelError.setText("Lade till lärare");
                        }else{
                            jLabelError.setText("Det finns en andvändare som har dem tre första bokstäverna i för och efternamn vänligen be om att bli omdöpt");
                        }
                    } catch (InfException ex) {
                        jLabelError.setText("SQL Fel: " + ex.getMessage());
                
                    }
                }
            }else{
                jLabelError.setText("Förnamnet och efternamnet får ej inehålla mellanrumm eller siffror");
            }
        }
        
    }//GEN-LAST:event_jButtonLaggTillActionPerformed

    private void jCheckBoxAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAdminActionPerformed
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_jCheckBoxAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLaggTill;
    private javax.swing.JCheckBox jCheckBoxAdmin;
    private javax.swing.JLabel jLabelEfternamn;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelFornamn;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelLosenord;
    private javax.swing.JTextField jTextFieldEfternamn;
    private javax.swing.JTextField jTextFieldFornamn;
    private javax.swing.JTextField jTextFieldLosenord;
    // End of variables declaration//GEN-END:variables
}
