/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny.AdminMeny.Larare;

import hogwarts.LararMeny.AdminMeny.Larare.AndraLarare.AndraLarare;
import oru.inf.InfDB;

/**
 * En samlingspunkt för klasser som har med lärare att göra.
 */
public class TabbadLarare extends javax.swing.JPanel {
    private RegistreraLarare registreraLarare = null;
    private AndraLarare andraLarare = null;
    
    private InfDB db;
    /**
     * Creates new form Larare
     */
    public TabbadLarare(InfDB db) {
        this.db = db;
        registreraLarare = new RegistreraLarare(db);
        andraLarare = new AndraLarare(db);
        initComponents();
        
        
        jTabbedPaneLarare.add("Registrera lärare", registreraLarare);
        jTabbedPaneLarare.add("Andra lärare", andraLarare);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneLarare = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneLarare, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneLarare, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneLarare;
    // End of variables declaration//GEN-END:variables
}
