/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import hogwarts.LararMeny.LararForm;
import hogwarts.ElevMeny.ElevForm;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Här är klassen för login rutan. Beroende på vad man gör här kommer en ruta
 * visas upp efter man tryck på en av de två knapparna. Den som heter
 * "logga in som elev" startar upp delen för icke inloggade användare.
 * Loggar man in med användarnamn och lösenord får man fram lärarmenyn.
 * Är användaren dessutom admin så kommer man komma åt fler val efteråt.
 */
public class LoginForm extends javax.swing.JFrame {
    private InfDB db;
    /**
     * Creates new form LoginForm
     */
    public LoginForm(InfDB db) {
        initComponents();
        this.db = db;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonLarare = new javax.swing.JButton();
        jButtonElev = new javax.swing.JButton();
        jLabelUsername = new javax.swing.JLabel();
        jTextUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabelPassword = new javax.swing.JLabel();
        hogwartsbild = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hogwarts Login");
        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonLarare.setText("Logga in som lärare");
        jButtonLarare.setAlignmentX(0.5F);
        jButtonLarare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonLarare.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLarare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLarareActionPerformed(evt);
            }
        });

        jButtonElev.setText("Logga in som Elev");
        jButtonElev.setAlignmentX(0.5F);
        jButtonElev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonElev.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElevActionPerformed(evt);
            }
        });

        jLabelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsername.setLabelFor(jLabelUsername);
        jLabelUsername.setText("Användare");
        jLabelUsername.setAlignmentX(0.5F);

        jTextUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsernameActionPerformed(evt);
            }
        });

        jPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPassword.setLabelFor(jPassword);
        jLabelPassword.setText("Lösenord");
        jLabelPassword.setAlignmentX(0.5F);

        hogwartsbild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hogwarts/Hogwartscrest.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButtonElev)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLarare))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(hogwartsbild, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(hogwartsbild)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLarare)
                    .addComponent(jButtonElev))
                .addGap(22, 22, 22))
        );

        jLabelError.setForeground(new java.awt.Color(204, 0, 0));
        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //hanteriung för klick på loginknappen
    private void jButtonLarareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLarareActionPerformed
        // TODO add your handlig code here:
        
        String username = jTextUsername.getText();
        
        String password = Util.stringFromCharArray(jPassword.getPassword());
        
        Validation.losenValidering result = Validation.valideraLösenord(db, username, password);
        
        if(null != result)switch (result) {
            case SUCCESSFULL:
                String treFornamn = username.substring(0, 3);
                String treEfternamn = username.substring(3, 6);
        
                try {
                    String res = db.fetchSingle("SELECT LARAR_ID FROM LARARE WHERE FORNAMN LIKE '" + treFornamn + "%' AND EFTERNAMN LIKE '" + treEfternamn + "%';");
                    new LararForm(db, Integer.parseInt(res)).setVisible(true);
                    this.setVisible(false);
                } catch (InfException ex) {
                    jLabelError.setText("Sql Fel");
                }
        
                
                
                break;
            case WRONG_USERNAME_FORMAT:
                 jLabelError.setText("Fel användarformat");
                
                break;
            case WRONG_PASSWORD:
                 jLabelError.setText("Fel lösenord");
                
                break;
            case NO_USER:
                 jLabelError.setText("Det finns ingen andvändare med det namnet");
                
                break;
            case SQL_ERROR:
                 jLabelError.setText("Sql Fel");
                
                break;
            default:
                break;
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonLarareActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
        jButtonLarare.doClick();
        jTextUsername.requestFocus();
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jTextUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsernameActionPerformed
        // TODO add your handling code here:
        jPassword.requestFocus();
    }//GEN-LAST:event_jTextUsernameActionPerformed

    private void jButtonElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElevActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ElevForm(db).setVisible(true);
        
    }//GEN-LAST:event_jButtonElevActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hogwartsbild;
    private javax.swing.JButton jButtonElev;
    private javax.swing.JButton jButtonLarare;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextUsername;
    // End of variables declaration//GEN-END:variables
}
