/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny.AdminMeny;

import hogwarts.Util;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 * Välj ett elevhem som du vill ändra prefekt och/eller föreståndare för.
 */
public class AndraElevhem extends javax.swing.JPanel {
    private InfDB db;
    /**
     * Creates new form ÄndraElevhem
     */
    public AndraElevhem(InfDB db) {
        this.db = db;
        initComponents();
        
        String[] elevhem = Util.elevhemsArray(db);
        for(int i = 0; i < elevhem.length; i++){
            jComboBoxElevhem.addItem(elevhem[i]);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxElevhem = new javax.swing.JComboBox<>();
        jLabelElevhem = new javax.swing.JLabel();
        jButtonValj = new javax.swing.JButton();

        jComboBoxElevhem.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabelElevhem.setText("Välj elevhem");

        jButtonValj.setText("välj");
        jButtonValj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelElevhem)
                    .addComponent(jButtonValj))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelElevhem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonValj)
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValjActionPerformed
        try {
            // TODO add your handling code here:

            int elevhemsID = Integer.parseInt(db.fetchSingle("SELECT ELEVHEM_ID FROM ELEVHEM WHERE ELEVHEMSNAMN = '" + jComboBoxElevhem.getSelectedItem().toString() + "';"));
            
            new AndraElevhemForm(db, elevhemsID).setVisible(true);
        } catch (InfException ex) {
            
        }
        
    }//GEN-LAST:event_jButtonValjActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValj;
    private javax.swing.JComboBox<String> jComboBoxElevhem;
    private javax.swing.JLabel jLabelElevhem;
    // End of variables declaration//GEN-END:variables
}
