/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny.AdminMeny;

import java.util.ArrayList;

import java.util.HashMap;
import javax.swing.JFrame;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Här kan man välja vem som är prefekt och föreståndare för det elevhem man valde i föregående meny.
 */
public class AndraElevhemForm extends javax.swing.JFrame {
    private InfDB db;
    int elevhemsID;
    /**
     * Creates new form ÄndraElevhemForm
     */
    public AndraElevhemForm(InfDB db, int elevhemsID) {
        this.db = db;
        this.elevhemsID = elevhemsID; 
        
        
        initComponents();
        ArrayList<String> elevLista = new ArrayList<>();
        try {
            //Plocka fram prefektkandidater
            ArrayList<HashMap<String, String>> result = db.fetchRows("SELECT FORNAMN, EFTERNAMN FROM ELEV JOIN SOVSAL ON SOVSAL = SOVSAL_ID WHERE ELEVHEM = " + elevhemsID +  ";");
            
            if(result != null){
                //Populera en temporär arraylist
               for(HashMap<String, String> row : result){
                   elevLista.add(row.get("FORNAMN") + " " + row.get("EFTERNAMN"));
               }
               
               //Populera comboboxen
               for(String elev : elevLista){
                    jComboBox1.addItem(elev);
            
                }
               
               //Välj den tidigare elevhemsprefekt i listan
                HashMap<String, String> tidigareElev = db.fetchRow("SELECT FORNAMN, EFTERNAMN FROM ELEV JOIN ELEVHEM ON PREFEKT = ELEV_ID WHERE ELEVHEM_ID = " + elevhemsID +  ";");
               
                String item;
                if(tidigareElev != null){
                    for (int i = 0; i < jComboBox1.getItemCount(); i++){
                        item = jComboBox1.getItemAt(i);
                        if (item.equals(tidigareElev.get("FORNAMN") + " " + tidigareElev.get("EFTERNAMN"))){
                            jComboBox1.setSelectedIndex(i);
                            break;
                        }
                    }
                }
                
            }
            
        } catch (InfException ex) {
            jLabelError.setText("Sql fel");
        }
        
   
        
        ArrayList<String> lararLista = new ArrayList<>();
        try {
            ArrayList<HashMap<String, String>> result = db.fetchRows("SELECT FORNAMN, EFTERNAMN FROM LARARE;");
            
            if(result != null){
                for(HashMap<String, String> row : result){
                    lararLista.add(row.get("FORNAMN") + " " + row.get("EFTERNAMN"));
                }
                
                for(String larare : lararLista){
                    jComboBox2.addItem(larare);
                }
                
                //Välj den tidigare elevhemsföreståndaren i listan
                HashMap<String, String> tidigareLarare = db.fetchRow("SELECT FORNAMN, EFTERNAMN FROM LARARE JOIN ELEVHEM ON FORESTANDARE = LARAR_ID WHERE ELEVHEM_ID = "+ elevhemsID + ";");
               
                String item;
                if(tidigareLarare != null){
                    for (int i = 0; i < jComboBox2.getItemCount(); i++){
                        item = jComboBox2.getItemAt(i);
                        if (item.equals(tidigareLarare.get("FORNAMN") + " " + tidigareLarare.get("EFTERNAMN"))){
                            jComboBox2.setSelectedIndex(i);
                            break;
                        }
                    }
                }
            }
            
            
        } catch (InfException ex) {
            jLabelError.setText("Sql fel");
        }
        
        
        
        //Hantera fönsterstängning 
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelElevhem = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelPrefekt = new javax.swing.JLabel();
        jLabelForestandare = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButtonUppdatera = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelElevhem.setText("Elevhem");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabelPrefekt.setText("Elevhemsprefekt ");

        jLabelForestandare.setText("Elevhemsföreståndare");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>());

        jButtonUppdatera.setText("ändra");
        jButtonUppdatera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUppdateraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelElevhem)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPrefekt)
                        .addGap(15, 15, 15)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelForestandare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonUppdatera)
                    .addComponent(jLabelError))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelElevhem)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrefekt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelForestandare)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonUppdatera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jLabelError))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        //Hantera fönsterstängning
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonUppdateraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUppdateraActionPerformed
        //förbered id hämning från namn
        String prefektVal = (String)jComboBox1.getSelectedItem();
        String[] prefektNamn = prefektVal.split(" ");
        String lararVal = (String)jComboBox2.getSelectedItem();
        
        String[] lararNamn = lararVal.split(" ");
        try {
            //hitta elevens id
            String prefektID = db.fetchSingle("SELECT ELEV_ID FROM ELEV WHERE FORNAMN = '" + prefektNamn[0] +  "' AND EFTERNAMN = '" + prefektNamn[1] + "'");
        
            //updatera prefekten
            db.update("UPDATE ELEVHEM SET PREFEKT = " + prefektID + " WHERE ELEVHEM_ID = " + elevhemsID + ";");
            
            //hitta lärarens id
            String LarareID = db.fetchSingle("SELECT LARAR_ID FROM LARARE WHERE FORNAMN = '" + lararNamn[0] +  "' AND EFTERNAMN = '" + lararNamn[1] + "'");
        
            //updatera föreståndaren
            db.update("UPDATE ELEVHEM SET FORESTANDARE = " + LarareID + " WHERE ELEVHEM_ID = " + elevhemsID + ";");
            
        } catch (InfException ex) {
            jLabelError.setText("Sql fel:" + ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_jButtonUppdateraActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUppdatera;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabelElevhem;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelForestandare;
    private javax.swing.JLabel jLabelPrefekt;
    // End of variables declaration//GEN-END:variables
}
