/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.LararMeny.AdminMeny.Larare.AndraLarare;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Väljer en lärare som du kan gå in och ändra för. Detta öppnar upp AndraLararForm
 */
public class AndraLarare extends javax.swing.JPanel {
    private InfDB db;
    /**
     * Creates new form AndraLarare
     */
    public AndraLarare(InfDB db) {
        this.db = db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldFornamn = new javax.swing.JTextField();
        jLabelFornamn = new javax.swing.JLabel();
        jLabelEfternamn = new javax.swing.JLabel();
        jTextFieldEfternamn = new javax.swing.JTextField();
        jButtonValj = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();

        jLabelFornamn.setText("Förnamn");

        jLabelEfternamn.setText("Efternamn:");

        jButtonValj.setText("Välj");
        jButtonValj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValjActionPerformed(evt);
            }
        });

        jLabelInfo.setText("Ändra lärare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelFornamn)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldFornamn))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelEfternamn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonValj)
                    .addComponent(jLabelInfo)
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFornamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEfternamn)
                    .addComponent(jTextFieldEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonValj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValjActionPerformed
        // TODO add your handling code here:
        
        String fornamn = jTextFieldFornamn.getText();
        String efternamn = jTextFieldEfternamn.getText();
        
        //Denna väljer lärar id:t där ett förnamn och efternamn stämmer överens.
        try {
            String stringId = db.fetchSingle("SELECT LARAR_ID FROM LARARE WHERE FORNAMN = '" + fornamn + "' AND EFTERNAMN = '" + efternamn + "';");
            
            if(stringId != null){
                int id = Integer.parseInt(stringId);
                
                new AndraLarareForm(db, id).setVisible(true);


                //återställ felmedelandena
                jLabelError.setText("");
                
            }else{
                jLabelError.setText("Andvändaren existerar inte!");
            }
        } catch (InfException ex) {
            jLabelError.setText("Sql fel!");
        }
    }//GEN-LAST:event_jButtonValjActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValj;
    private javax.swing.JLabel jLabelEfternamn;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelFornamn;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JTextField jTextFieldEfternamn;
    private javax.swing.JTextField jTextFieldFornamn;
    // End of variables declaration//GEN-END:variables
}
