/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.ElevMeny;


import oru.inf.InfDB;


/**
 *Denna del är den som visar alla tabbar för elevinlogg, och instansierar dem.
 *
 */
public class ElevForm extends javax.swing.JFrame {
    private ElevhemsPoang poang;
    private HittaPrefekt hittaPrefekt;
    private ElevKurser elevKurser;
    private ElevhemsElever elevhemsElever;
    private LararKurser lararKurser;
    private InfDB db;
    /**
     * Creates new form ElevForm
     * @param db
     */
    
    //Här tar vi och ska
    public ElevForm(InfDB db) {
        poang = new ElevhemsPoang(db);
        hittaPrefekt = new HittaPrefekt(db);
        elevKurser = new ElevKurser(db);
        elevhemsElever = new ElevhemsElever(db);
        lararKurser = new LararKurser(db);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //Här hittar vi namnen som vi ger till alla tabbar. (i denna genererade kod)
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedElev = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hogwats");

        jTabbedElev.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedElev.setToolTipText("");

        jTabbedElev.add("Elevhem", poang);
        jTabbedElev.add("Hitta prefekter", hittaPrefekt);
        jTabbedElev.add("ElevsKurser", elevKurser);
        jTabbedElev.add("Elevhems elever", elevhemsElever);
        jTabbedElev.add("Lärares kurser", lararKurser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedElev)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedElev)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedElev;
    // End of variables declaration//GEN-END:variables
}
