/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hogwarts.ElevMeny;


import hogwarts.Util;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Här kan vi se elevhemsställningen i den årliga elevhems tävlingen.
 */
public class ElevhemsPoang extends javax.swing.JPanel {
    private InfDB db;
    
    String[][] poangArray;
    String[] sektionsArray;
    /** Creates new form ElevhemsPoang */
    public ElevhemsPoang(InfDB db) {
        
        //skapar arraylistor för sektioner och poäng.
        ArrayList<String> sektioner = new ArrayList<String>();
        ArrayList<String> poang = new ArrayList<String>();
        
        //Fyller upp alla delar med hjälp av att ha koll på elevhemmen och deras poäng.
        try {
            ArrayList<HashMap<String, String>> result = db.fetchRows("SELECT ELEVHEMSNAMN, HUSPOANG FROM ELEVHEM;");
            
            for(HashMap<String, String> row : result){
                
                sektioner.add(row.get("ELEVHEMSNAMN"));
                poang.add(row.get("HUSPOANG"));
            
            }
        } catch (InfException ex) {
            
        }
        
        poangArray = new String[1][poang.size()];
        for(int i = 0; i < poang.size(); i++){
            poangArray[0][i] = poang.get(i);
        }
        sektionsArray = Util.konverteraArrayListTillArray(sektioner);
        
        initComponents();
        
        
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableElevhemsStallning = new JTable();
        jLabelInfo = new javax.swing.JLabel();

        jTableElevhemsStallning.setModel(new DefaultTableModel(
            poangArray,
            sektionsArray

        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jScrollPane1.setViewportView(jTableElevhemsStallning);

    jLabelInfo.setText("Nuvarande Elevhemsställning");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelInfo))
            .addContainerGap(15, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addComponent(jLabelInfo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(208, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableElevhemsStallning;
    // End of variables declaration//GEN-END:variables

}
