/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts.ElevMeny;

import hogwarts.Util;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *  Denna del visar upp prefekt(er) för respektive elevhem.
 * 
 */
public class HittaPrefekt extends javax.swing.JPanel {
    private InfDB db;
    
    private String[][] data = null;
    private String[] elevhem = null;
    /**
     * Creates new form HittaPrefekt
     */
    public HittaPrefekt(InfDB db) {
        this.db = db;
        
        
        
        elevhem = Util.elevhemsArray(db);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfo = new javax.swing.JLabel();
        jComboBoxElevhem = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableElevhemsprefekter = new javax.swing.JTable();
        jLabelError = new javax.swing.JLabel();

        jLabelInfo.setText("Välj ett elevhem så får du se vilka som är prefekter för dem");

        jComboBoxElevhem.setModel(new javax.swing.DefaultComboBoxModel<>(elevhem));
        jComboBoxElevhem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxElevhemActionPerformed(evt);
            }
        });

        jTableElevhemsprefekter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Förnamn", "Efternamn"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTableElevhemsprefekter.getTableHeader().setReorderingAllowed(false);
    jScrollPane2.setViewportView(jTableElevhemsprefekter);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelInfo)))
            .addContainerGap(15, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(jLabelInfo)
            .addGap(18, 18, 18)
            .addComponent(jComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
            .addComponent(jLabelError))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxElevhemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxElevhemActionPerformed
        // TODO add your handling code here:
       
        //Uppdatatera tabellen med prefekter för rätt elevhem.
        // Vi åstadkommer detta genom att joina elever som är prefekter på elevhemmen.
        try {
            ArrayList<HashMap<String, String>> result = db.fetchRows("SELECT FORNAMN, EFTERNAMN FROM ELEVHEM JOIN ELEV ON PREFEKT = ELEV_ID where ELEVHEMSNAMN = '" + jComboBoxElevhem.getSelectedItem().toString() + "';");
            //hämta ut tabelldatan
            DefaultTableModel model = (DefaultTableModel) jTableElevhemsprefekter.getModel();
            model.setRowCount(0);
            if(result != null){
                for(HashMap<String, String> row : result){
                    //Lägg till rader 
                    model.addRow(new String[] {row.get("FORNAMN"), row.get("EFTERNAMN")});
                }
                jTableElevhemsprefekter.setModel(model); 
            }else{
                //det finns inga prefekter i det elevhemmet
                jLabelError.setText("Det finns inga prefekter i elevhemmet!");
            }
        } catch (InfException ex) {
            //Något gick fel i databasen
             jLabelError.setText("Databasfel: " + ex.getMessage());
        }
        
        
    }//GEN-LAST:event_jComboBoxElevhemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxElevhem;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableElevhemsprefekter;
    // End of variables declaration//GEN-END:variables
}
